"""make id default to uuid

Revision ID: 60e196dee193
Revises: 28611dcf97fc
Create Date: 2025-07-02 10:36:46.907195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60e196dee193'
down_revision: Union[str, Sequence[str], None] = '28611dcf97fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_playlist_id'), 'playlist', ['id'], unique=False)
    op.create_index(op.f('ix_playlistsonglink_id'), 'playlistsonglink', ['id'], unique=False)
    op.create_index(op.f('ix_song_id'), 'song', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_song_id'), table_name='song')
    op.drop_index(op.f('ix_playlistsonglink_id'), table_name='playlistsonglink')
    op.drop_index(op.f('ix_playlist_id'), table_name='playlist')
    # ### end Alembic commands ###
